--
-- Supermarket Database Schema for Oracle 19c
-- Adapted from ER/Studio 8.0 original
-- Modernized with IDENTITY columns and other 19c features
--

-- 
-- TABLE: acceso_usuario 
--

CREATE TABLE acceso_usuario(
    ide_acce             NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_cuen             NUMBER(38)      NOT NULL,
    fecha_acce           DATE            NOT NULL,
    num_intentos_acce    NUMBER(38)      NOT NULL,
    ip_acce              VARCHAR2(50)    NOT NULL,
    navegador_acce       VARCHAR2(250)   NOT NULL,
    latitud_acce         NUMBER(38),
    longitud_acce        NUMBER(38),
    CONSTRAINT PK18 PRIMARY KEY (ide_acce)
);

-- 
-- TABLE: categoria 
--

CREATE TABLE categoria(
    ide_cate            NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre_cate         VARCHAR2(100)   NOT NULL,
    descripcion_cate    VARCHAR2(250)   NOT NULL,
    usua_ingre          VARCHAR2(25),
    fecha_ingre         DATE,
    usua_actua          VARCHAR2(25),
    fecha_actua         DATE,
    CONSTRAINT PK7 PRIMARY KEY (ide_cate)
);

-- 
-- TABLE: cliente 
--

CREATE TABLE cliente(
    ide_clie                 NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    cedula_clie              VARCHAR2(15)    NOT NULL,
    primer_nombre_clie       VARCHAR2(50)    NOT NULL,
    segundo_nombre_clie      VARCHAR2(50)    NOT NULL,
    apellido_paterno_clie    VARCHAR2(50)    NOT NULL,
    apellido_materno_clie    VARCHAR2(50)    NOT NULL,
    fecha_nacimiento_clie    DATE            NOT NULL,
    edad_clie                NUMBER(38)      NOT NULL,
    telefono_clie            VARCHAR2(15)    NOT NULL,
    email_clie               VARCHAR2(50)    NOT NULL,
    es_socio                 VARCHAR2(2)     NOT NULL,
    es_tercera_edad          VARCHAR2(2)     NOT NULL,
    usua_ingre               VARCHAR2(25),
    fecha_ingre              DATE,
    usua_actua               VARCHAR2(15),
    fecha_actua              DATE,
    CONSTRAINT PK5 PRIMARY KEY (ide_clie)
);

-- 
-- TABLE: cuenta 
--

CREATE TABLE cuenta(
    ide_cuen         NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_empl         NUMBER(38)      NOT NULL,
    ide_perf         NUMBER(38)      NOT NULL,
    usuario_cuen     VARCHAR2(25)    NOT NULL,
    password_cuen    VARCHAR2(25)    NOT NULL,
    estado_cuen      VARCHAR2(25)    NOT NULL,
    usua_ingre       VARCHAR2(25),
    fecha_ingre      DATE,
    usua_actua       VARCHAR2(25),
    fecha_actua      DATE,
    CONSTRAINT PK17 PRIMARY KEY (ide_cuen)
);

-- 
-- TABLE: detalle_entrega 
--

CREATE TABLE detalle_entrega(
    ide_deta_entr           NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_entr                NUMBER(38)      NOT NULL,
    ide_prod                NUMBER(38)      NOT NULL,
    cantidad_prod           NUMBER(38)      NOT NULL,
    precio_unitario_prod    NUMBER(10, 2)   NOT NULL,
    dcto_prod               NUMBER(10, 2)   NOT NULL,
    iva_prod                NUMBER(10, 2)   NOT NULL,
    subtotal_prod           NUMBER(10, 2)   NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (ide_deta_entr)
);

-- 
-- TABLE: detalle_pedido 
--

CREATE TABLE detalle_pedido(
    ide_deta_pedi           NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_prod                NUMBER(38)      NOT NULL,
    ide_pedi                NUMBER(38)      NOT NULL,
    cantidad_prod           NUMBER(38)      NOT NULL,
    precio_unitario_prod    NUMBER(10, 2)   NOT NULL,
    dcto_prod               NUMBER(10, 2)   NOT NULL,
    iva_prod                NUMBER(10, 2)   NOT NULL,
    subtotal_prod           NUMBER(10, 2)   NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (ide_deta_pedi)
);

-- 
-- TABLE: detalle_venta 
--

CREATE TABLE detalle_venta(
    ide_deta_vent           NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_vent                NUMBER(38)      NOT NULL,
    ide_prod                NUMBER(38)      NOT NULL,
    cantidad_prod           NUMBER(38)      NOT NULL,
    precio_unitario_prod    NUMBER(10, 2)   NOT NULL,
    dcto_prod               NUMBER(10, 2)   NOT NULL,
    dcto_promo              NUMBER(10, 2)   NOT NULL,
    iva_prod                NUMBER(10, 2)   NOT NULL,
    subtotal_prod           NUMBER(10, 2)   NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (ide_deta_vent)
);

-- 
-- TABLE: empleado 
--

CREATE TABLE empleado(
    ide_empl                 NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_rol                  NUMBER(38)      NOT NULL,
    cedula_empl              VARCHAR2(15)    NOT NULL,
    primer_nombre_empl       VARCHAR2(50)    NOT NULL,
    segundo_nombre_empl      VARCHAR2(50)    NOT NULL,
    apellido_paterno_empl    VARCHAR2(50)    NOT NULL,
    apellido_materno_empl    VARCHAR2(50)    NOT NULL,
    fecha_nacimiento_empl    DATE            NOT NULL,
    edad_empl                NUMBER(38)      NOT NULL,
    fecha_inicio_empl        DATE            NOT NULL,
    rmu_empl                 NUMBER(10, 2)   NOT NULL,
    fecha_termino_empl       DATE,
    usua_ingre               VARCHAR2(25),
    fecha_ingre              DATE,
    usua_actua               VARCHAR2(25),
    fecha_actua              DATE,
    CONSTRAINT PK15 PRIMARY KEY (ide_empl)
);

-- 
-- TABLE: empresa 
--

CREATE TABLE empresa(
    ide_empr               NUMBER(38)       GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre_empr            VARCHAR2(500)    NOT NULL,
    responsable_empr       VARCHAR2(250)    NOT NULL,
    direccion_empr         VARCHAR2(1000)   NOT NULL,
    telefono_empr          VARCHAR2(15)     NOT NULL,
    email_empr             VARCHAR2(50)     NOT NULL,
    fecha_contrato_empr    DATE             NOT NULL,
    estado_empr            VARCHAR2(25)     NOT NULL,
    usua_ingre             VARCHAR2(25),
    fecha_ingre            DATE,
    usua_actua             VARCHAR2(25),
    fecha_actua            DATE,
    CONSTRAINT PK3 PRIMARY KEY (ide_empr)
);

-- 
-- TABLE: empresa_precios 
--

CREATE TABLE empresa_precios(
    ide_empr_prod          NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_empr               NUMBER(38)      NOT NULL,
    ide_prod               NUMBER(38)      NOT NULL,
    precio_compra_prod     NUMBER(10, 2)   NOT NULL,
    dcto_compra_prod       NUMBER(10, 2)   NOT NULL,
    iva_prod               NUMBER(10, 2)   NOT NULL,
    dcto_caducidad_prod    NUMBER(10, 2)   NOT NULL,
    usua_ingre             VARCHAR2(25),
    fecha_ingre            DATE,
    usua_actua             VARCHAR2(25),
    fecha_actua            DATE,
    CONSTRAINT PK28 PRIMARY KEY (ide_empr_prod)
);

-- 
-- TABLE: entrega 
--

CREATE TABLE entrega(
    ide_entr               NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_prov               NUMBER(38)      NOT NULL,
    ide_pedi               NUMBER(38)      NOT NULL,
    fecha_entr             DATE            NOT NULL,
    cantidad_total_entr    NUMBER(38)      NOT NULL,
    total_entr             NUMBER(10, 2)   NOT NULL,
    estado_entr            VARCHAR2(25)    NOT NULL,
    observacion_entr       VARCHAR2(250)   NOT NULL,
    usua_ingre             VARCHAR2(25),
    fecha_ingre            DATE,
    usua_actua             VARCHAR2(25),
    fecha_actua            DATE,
    CONSTRAINT PK11 PRIMARY KEY (ide_entr)
);

-- 
-- TABLE: lote 
--

CREATE TABLE lote(
    ide_lote                NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_prod                NUMBER(38)      NOT NULL,
    stock_lote              NUMBER(38)      NOT NULL,
    estado_lote             VARCHAR2(100)   NOT NULL,
    fecha_caducidad_lote    DATE            NOT NULL,
    CONSTRAINT PK27 PRIMARY KEY (ide_lote)
);

-- 
-- TABLE: marca 
--

CREATE TABLE marca(
    ide_marc            NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre_marc         VARCHAR2(100)   NOT NULL,
    pais_origen_marc    VARCHAR2(100)   NOT NULL,
    descripcion_marc    VARCHAR2(250)   NOT NULL,
    usua_ingre          VARCHAR2(25),
    fecha_ingre         DATE,
    usua_actua          VARCHAR2(25),
    fecha_actua         DATE,
    CONSTRAINT PK8 PRIMARY KEY (ide_marc)
);

-- 
-- TABLE: opciones 
--

CREATE TABLE opciones(
    ide_opci            NUMBER(38)       GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre_opci         VARCHAR2(500)    NOT NULL,
    ruta_opci           VARCHAR2(500)    NOT NULL,
    activo_opci         VARCHAR2(2)      NOT NULL,
    descripcion_opci    VARCHAR2(1000)   NOT NULL,
    usua_ingre          VARCHAR2(25),
    fecha_ingre         DATE,
    usua_actua          VARCHAR2(25),
    fecha_actua         DATE,
    CONSTRAINT PK25 PRIMARY KEY (ide_opci)
);

-- 
-- TABLE: pedido 
--

CREATE TABLE pedido(
    ide_pedi               NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_empr               NUMBER(38)      NOT NULL,
    fecha_pedi             DATE            NOT NULL,
    fecha_entr_pedi        DATE            NOT NULL,
    cantidad_total_pedi    NUMBER(38)      NOT NULL,
    total_pedi             NUMBER(10, 2)   NOT NULL,
    estado_pedi            VARCHAR2(25)    NOT NULL,
    motivo_pedi            VARCHAR2(250)   NOT NULL,
    observacion_pedi       VARCHAR2(250)   NOT NULL,
    usua_ingre             VARCHAR2(25),
    fecha_ingre            DATE,
    usua_actua             VARCHAR2(25),
    fecha_actua            DATE,
    CONSTRAINT PK9 PRIMARY KEY (ide_pedi)
);

-- 
-- TABLE: perfil 
--

CREATE TABLE perfil(
    ide_perf            NUMBER(38)       GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_rol             NUMBER(38)       NOT NULL,
    nombre_perf         VARCHAR2(1000)   NOT NULL,
    descripcion_perf    VARCHAR2(1000)   NOT NULL,
    usua_ingre          VARCHAR2(25),
    fecha_ingre         DATE,
    usua_actua          VARCHAR2(25),
    fecha_actua         DATE,
    CONSTRAINT PK24 PRIMARY KEY (ide_perf)
);

-- 
-- TABLE: perfil_opciones 
--

CREATE TABLE perfil_opciones(
    ide_perf_opci    NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_perf         NUMBER(38)      NOT NULL,
    ide_opci         NUMBER(38)      NOT NULL,
    listar           VARCHAR2(2)     NOT NULL,
    insertar         VARCHAR2(2)     NOT NULL,
    modificar        VARCHAR2(2)     NOT NULL,
    eliminar         VARCHAR2(2)     NOT NULL,
    usua_ingre       VARCHAR2(25),
    fecha_ingre      DATE,
    usua_actua       VARCHAR2(25),
    fecha_actua      DATE,
    CONSTRAINT PK26 PRIMARY KEY (ide_perf_opci)
);

-- 
-- TABLE: producto 
--

CREATE TABLE producto(
    ide_prod              NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_cate              NUMBER(38)      NOT NULL,
    ide_marc              NUMBER(38)      NOT NULL,
    codigo_barra_prod     VARCHAR2(30)    NOT NULL,
    nombre_prod           VARCHAR2(250)   NOT NULL,
    precio_compra_prod    NUMBER(10, 2)   NOT NULL,
    precio_venta_prod     NUMBER(10, 2)   NOT NULL,
    iva_prod              NUMBER(10, 2)   NOT NULL,
    dcto_caduc_prod       NUMBER(10, 2)   NOT NULL,
    stock_prod            NUMBER(38)      NOT NULL,
    dcto_promo_prod       NUMBER(10, 2)   NOT NULL,
    disponible_prod       VARCHAR2(25)    NOT NULL,
    estado_prod           VARCHAR2(25)    NOT NULL,
    descripcion_prod      VARCHAR2(250)   NOT NULL,
    usua_ingre            VARCHAR2(25),
    fecha_ingre           DATE,
    usua_actua            VARCHAR2(25),
    fecha_actua           DATE,
    CONSTRAINT PK6 PRIMARY KEY (ide_prod)
);

-- 
-- TABLE: proveedor 
--

CREATE TABLE proveedor(
    ide_prov                 NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_empr                 NUMBER(38)      NOT NULL,
    cedula_prov              VARCHAR2(15)    NOT NULL,
    primer_nombre_prov       VARCHAR2(50)    NOT NULL,
    segundo_nombre_prov      VARCHAR2(50)    NOT NULL,
    apellido_paterno_prov    VARCHAR2(50)    NOT NULL,
    apellido_materno_prov    VARCHAR2(50)    NOT NULL,
    fecha_nacimiento_prov    DATE            NOT NULL,
    edad_prov                NUMBER(38)      NOT NULL,
    telefono_prov            VARCHAR2(15)    NOT NULL,
    email_prov               VARCHAR2(50)    NOT NULL,
    usua_ingre               VARCHAR2(25),
    fecha_ingre              DATE,
    usua_actua               VARCHAR2(25),
    fecha_actua              DATE,
    CONSTRAINT PK4 PRIMARY KEY (ide_prov)
);

-- 
-- TABLE: rol 
--

CREATE TABLE rol(
    ide_rol            NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre_rol         VARCHAR2(250)   NOT NULL,
    descripcion_rol    VARCHAR2(250)   NOT NULL,
    usua_ingre         VARCHAR2(25),
    fecha_ingre        DATE,
    usua_actua         VARCHAR2(25),
    fecha_actua        DATE,
    CONSTRAINT PK16 PRIMARY KEY (ide_rol)
);

-- 
-- TABLE: venta 
--

CREATE TABLE venta(
    ide_vent            NUMBER(38)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ide_clie            NUMBER(38)      NOT NULL,
    ide_empl            NUMBER(38)      NOT NULL,
    num_factura_vent    VARCHAR2(25)    NOT NULL,
    fecha_vent          DATE            NOT NULL,
    sub_total_vent      NUMBER(10, 2)   NOT NULL,
    dcto_vent           NUMBER(10, 2)   NOT NULL,
    total_vent          NUMBER(10, 2)   NOT NULL,
    estado_vent         VARCHAR2(25)    NOT NULL,
    usua_ingre          VARCHAR2(25),
    fecha_ingre         DATE,
    usua_actua          VARCHAR2(25),
    fecha_actua         DATE,
    CONSTRAINT PK13 PRIMARY KEY (ide_vent)
);

-- Foreign Key Constraints (unchanged from original)

ALTER TABLE acceso_usuario ADD CONSTRAINT Refcuenta33 
    FOREIGN KEY (ide_cuen)
    REFERENCES cuenta(ide_cuen);

ALTER TABLE cuenta ADD CONSTRAINT Refempleado32 
    FOREIGN KEY (ide_empl)
    REFERENCES empleado(ide_empl);

ALTER TABLE cuenta ADD CONSTRAINT Refperfil39 
    FOREIGN KEY (ide_perf)
    REFERENCES perfil(ide_perf);

ALTER TABLE detalle_entrega ADD CONSTRAINT Refentrega23 
    FOREIGN KEY (ide_entr)
    REFERENCES entrega(ide_entr);

ALTER TABLE detalle_entrega ADD CONSTRAINT Refproducto24 
    FOREIGN KEY (ide_prod)
    REFERENCES producto(ide_prod);

ALTER TABLE detalle_pedido ADD CONSTRAINT Refpedido21 
    FOREIGN KEY (ide_pedi)
    REFERENCES pedido(ide_pedi);

ALTER TABLE detalle_pedido ADD CONSTRAINT Refproducto22 
    FOREIGN KEY (ide_prod)
    REFERENCES producto(ide_prod);

ALTER TABLE detalle_venta ADD CONSTRAINT Refproducto25 
    FOREIGN KEY (ide_prod)
    REFERENCES producto(ide_prod);

ALTER TABLE detalle_venta ADD CONSTRAINT Refventa26 
    FOREIGN KEY (ide_vent)
    REFERENCES venta(ide_vent);

ALTER TABLE empleado ADD CONSTRAINT Refrol30 
    FOREIGN KEY (ide_rol)
    REFERENCES rol(ide_rol);

ALTER TABLE empresa_precios ADD CONSTRAINT Refempresa41 
    FOREIGN KEY (ide_empr)
    REFERENCES empresa(ide_empr);

ALTER TABLE empresa_precios ADD CONSTRAINT Refproducto42 
    FOREIGN KEY (ide_prod)
    REFERENCES producto(ide_prod);

ALTER TABLE entrega ADD CONSTRAINT Refproveedor19 
    FOREIGN KEY (ide_prov)
    REFERENCES proveedor(ide_prov);

ALTER TABLE entrega ADD CONSTRAINT Refpedido20 
    FOREIGN KEY (ide_pedi)
    REFERENCES pedido(ide_pedi);

ALTER TABLE lote ADD CONSTRAINT Refproducto40 
    FOREIGN KEY (ide_prod)
    REFERENCES producto(ide_prod);

ALTER TABLE pedido ADD CONSTRAINT Refempresa18 
    FOREIGN KEY (ide_empr)
    REFERENCES empresa(ide_empr);

ALTER TABLE perfil ADD CONSTRAINT Refrol36 
    FOREIGN KEY (ide_rol)
    REFERENCES rol(ide_rol);

ALTER TABLE perfil_opciones ADD CONSTRAINT Refperfil37 
    FOREIGN KEY (ide_perf)
    REFERENCES perfil(ide_perf);

ALTER TABLE perfil_opciones ADD CONSTRAINT Refopciones38 
    FOREIGN KEY (ide_opci)
    REFERENCES opciones(ide_opci);

ALTER TABLE producto ADD CONSTRAINT Refcategoria28 
    FOREIGN KEY (ide_cate)
    REFERENCES categoria(ide_cate);

ALTER TABLE producto ADD CONSTRAINT Refmarca29 
    FOREIGN KEY (ide_marc)
    REFERENCES marca(ide_marc);

ALTER TABLE proveedor ADD CONSTRAINT Refempresa17 
    FOREIGN KEY (ide_empr)
    REFERENCES empresa(ide_empr);

ALTER TABLE venta ADD CONSTRAINT Refcliente27 
    FOREIGN KEY (ide_clie)
    REFERENCES cliente(ide_clie);

ALTER TABLE venta ADD CONSTRAINT Refempleado31 
    FOREIGN KEY (ide_empl)
    REFERENCES empleado(ide_empl);